name: flamethrower
namespace: kube-system
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/flame  # matches upstream image naming https://hub.docker.com/r/ns1labs/flame
  tag: 0.11.0
  pullPolicy: IfNotPresent
